config/routes.rb
Rails.application.routes.draw do
  
  devise_for :anglers, controllers: {
    sessions:      'anglers/sessions',
    passwords:     'anglers/passwords',
    registrations: 'anglers/registrations'
    }

    devise_for :agents, controllers: {
      sessions:      'agents/sessions',
      passwords:     'agents/passwords',
      registrations: 'agents/registrations'
    }
    root  'top#index'
    resources :agents, only: [:show,:edit,:update,:index]
    resources :blogs
    resources :posts, only: [:new, :create, :index, :show, :edit, :update, :destroy]

    get  'agents/prefecture_id/tokyo',  to: 'agents#agent_pref_index'

end

app/controllers/top_controller.rb
class TopController < ApplicationController

  def index
    @agent = current_agent
    @blogs = Blog.all.order(created_at: :desc).limit(5)
    @posts = Post.all.order(created_at: :desc).limit(5)
  end
  
end

app/helpers/top_helper.rb
module TopHelper
end

app/views/top/index.html.erb
<div class = 'content'>
<div class = 'main-top-content'>
    <div class = 'main-top-left-content'>
        <div class = 'shiping-agent-jmap-title'>
        船宿を探す
        </div>
        <div class= 'japan-map'>
        <%= render 'shared/japan_map' %>
        </div>
        <%#<%= link_to '仮東京', agents_prefecture_id_tokyo_path %>
    </div>
    <div class = 'main-top-right-content'>
        <% if  agent_signed_in? %>
            <% if @agent.image?%>
            <%= image_tag @agent.image.url , class: "icon_image" %> 
            <% else %>
            <%= image_tag 'no_image.png', class: "icon_image" %>
            <% end %>
        <% end %>
        <% if angler_signed_in? %>
        <!--釣果登録ユーザーは表示させない-->
        <div class = 'shipping-agent-sign-up'>
                <%= link_to '釣果を投稿する＞', new_post_path, class: "shipping-agent-sign-up-a" %>
            </div>
        <% elsif agent_signed_in? %>
        <div class = 'shipping-agent-sign-up'>
                <%= link_to '船宿ブログ投稿はこちら', new_blog_path, class: "shipping-agent-sign-up-a" %>
            </div>
            <div class = 'shipping-agent-sign-in'>
                <%= link_to '船宿さんログアウト>', destroy_agent_session_path, method: :delete, class: "shipping-agent-sign-in-a" %>
            </div>
        <% else %>
            <div class = 'shipping-agent-sign-up'>
                <%= link_to '船宿の新規登録はこちら', new_agent_registration_path, class: "shipping-agent-sign-up-a" %>
            </div>
            <div class = 'shipping-agent-sign-in'>
                <%= link_to '船宿さんログイン>', new_agent_session_path, class: "shipping-agent-sign-in-a" %>
            </div>
        <% end %>
        <div class = 'result-search'>
            <%= image_tag '釣果検索背景.jpeg'%>
            <a href="#"><i class="" ></i> 釣果検索</a>
        </div>
        <div class ='admin-notice'>
            <div class ='notice-title'> 
                お知らせ
            </div>
            <ul class= 'admin-notice-list'>
                <li>これはお知らせです①</li>
                <li>これはお知らせです②</li>
            </ul>
        </div>
    </div>
</div>
<div class = 'main-bottom-content'>
    <div class = 'main-bottom-left-content'>
        <div class = 'main-result-slider-title'>
        最新釣果
        </div>
            <div class="previews">
                <div class="slider">
                <%#<% if @posts.present? %>
                <% @posts.each do |post| %>
                        <li class='blog-list'>
                        <%= link_to post_path(post) do %>
                        <div class ='blog-content'>
                            <%= image_tag post.image , class: "blog-img-thumb" %>
                            <p class ='blog-title-thumb'><%= post.post_title %></p>
                        </div>
                        <% end %>
                        </li>
                <% end %>
                <%#<% end %>
                </div>
            </div>
            <div class='more-result'>
            <%= link_to 'もっとみる', posts_path , class: 'more-result-link'%>
            </div>
            <div class = 'main-result-slider-title'>
            最新ブログ
            </div>
            <div class="previews">
                <div class="slider">
                
                <% @blogs.each do |blog| %>
                        <li class='blog-list'>
                        <%= link_to blog_path(blog) do %>
                        <div class ='blog-content'>
                            <% if blog.image.present? %>
                                <%= image_tag blog.image , class: "blog-img-thumb" %>
                            <%else %>
                                <%= image_tag 'no_image.png', class:"blog-img-thumb" %>
                            <%end%>
                            
                            <p class ='blog-title-thumb'><%= blog.blog_title %></p>
                        </div>
                        <% end %>
                        </li>
                    <% end %>
                </div>
            </div>
            <div class='more-result'>
            <%= link_to 'もっとみる', blogs_path , class: 'more-result-link'%>
            </div>
            <div class = 'main-result-slider-title'>
            Any fish 通信
            </div>
            <div class="previews">
                <div class="slider">
                <%= image_tag "sakana_ao.png", class: "blog-img-thumb" %>
                <%= image_tag "sakana_ao.png", class: "blog-img-thumb" %>
                <%= image_tag "sakana_ao.png", class: "blog-img-thumb" %>
                <%= image_tag "sakana_ao.png", class: "blog-img-thumb" %>
                <%= image_tag "sakana_ao.png", class: "blog-img-thumb" %>
                <%= image_tag "sakana_ao.png", class: "blog-img-thumb" %>
                </div>
            </div>
            <div class='more-result'>
            <%= link_to 'もっとみる', '#' , class: 'more-result-link'%>
            </div>
    </div>
    <div class = 'main-bottom-right-content'>
        <div class = 'tide-graph'>
            <%= image_tag 'tide.jpeg'%>
            <a href="#"><i class="" ></i> タイドグラフ</a>
        </div>
        <div class='tackle-search'>
            <%= image_tag 'tackle.jpeg'%>
            <a href="#"><i class="" ></i> タックル検索</a>
        </div>
        <div class='fish-sreach'>
            <%= image_tag 'fish.jpeg'%>
            <a href="#"><i class="" ></i> 魚図鑑</a>
        </div>
        <div class ='fishing-guige'>
            <%= image_tag 'fishingguide.jpeg'%>
            <a href="#"><i class="" ></i> 釣りガイド</a>
        </div>
    </div>
</div>
</div>
<!-- これはHTML上でコメントアウトされた一文です -->