config/routes.rb
Rails.application.routes.draw do
  
  devise_for :anglers, controllers: {
    sessions:      'anglers/sessions',
    passwords:     'anglers/passwords',
    registrations: 'anglers/registrations'
    }

    devise_for :agents, controllers: {
      sessions:      'agents/sessions',
      passwords:     'agents/passwords',
      registrations: 'agents/registrations'
    }
    root  'top#index'
    resources :agents, only: [:show,:edit,:update,:index]
    resources :blogs
    resources :posts, only: [:new, :create, :index, :show, :edit, :update, :destroy]

    get  'agents/prefecture_id/tokyo',  to: 'agents#agent_pref_index'

end

app/models/agent.rb
class Agent < ApplicationRecord
  
  
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         mount_uploader :image, ImageUploader
        
          enum prefecture: {
          "--都道府県--":0,北海道:1,青森県:2,岩手県:3,宮城県:4,秋田県:5,山形県:6,福島県:7,
          茨城県:8,栃木県:9,群馬県:10,埼玉県:11,千葉県:12,東京都:13,神奈川県:14,
          新潟県:15,富山県:16,石川県:17,福井県:18,山梨県:19,長野県:20,
          岐阜県:21,静岡県:22,愛知県:23,三重県:24,
          滋賀県:25,京都府:26,大阪府:27,兵庫県:28,奈良県:29,和歌山県:30,
          鳥取県:31,島根県:32,岡山県:33,広島県:34,山口県:35,
          徳島県:36,香川県:37,愛媛県:38,高知県:39,
          福岡県:40,佐賀県:41,長崎県:42,熊本県:43,大分県:44,宮崎県:45,鹿児島県:46,沖縄県:47
        }, _prefix: true

        enum ship_type: {
          "--業種--":0,
          乗合:1,仕立:2,渡船:3,筏・カセ:4,レンタルボート:5,その他:6
        }, _prefix: true

        enum fishing_type: {
          "--釣り方--":0,
          コマセ（撒き餌）:1,サビキ:2,胴突き:3,活きエサ・泳がせ:4,天びん:5,五目釣り:6,磯釣り:7,
          筏・カセ釣り:8,スッテ・ツノ:9,エギング:10,タイラバ:11, ひとつテンヤ:12,ジギング・キャスティング:13,
          その他の釣り方:14
        }, _prefix: true

        with_options presence: true do
          validates :agentname, format: { with:/\A[ぁ-んァ-ン一-龥々ー]+\z/}
          validates :agentname_kana, format: { with: /\A[ァ-ヶー－]+\z/ }
          validates :email, on: :create
          VALID_PASSWORD_REGEX = /\A(?=.*?[a-z])(?=.*?[\d])[a-z\d]+\z/i
          validates :password, format: {with: VALID_PASSWORD_REGEX, message: "は英数字混合にしてください"}, on: :create
          validates :first_name, format: { with:/\A[ぁ-んァ-ン一-龥々ー]+\z/}
          validates :last_name, format: { with:/\A[ぁ-んァ-ン一-龥々ー]+\z/}
          validates :first_name_kana, format: { with: /\A[ァ-ヶー－]+\z/ }
          validates :last_name_kana, format: { with: /\A[ァ-ヶー－]+\z/ }
          validates :prefecture_id, numericality: {other_than: 0, message: "can't be blank"}
          validates :address
          validates :harbor
          validates :how_to_go1
          validates :tel1, format: {with:/\A\d{10,11}\z/, message: '電話番号は11桁以内の数値のみ保存可能なこと'}
          validates :regular_holiday
          validates :ice
          validates :target
          validates :ship_type_id, numericality: {other_than: 0, message: "can't be blank"}
          validates :fishing_type_id, numericality: {other_than: 0, message: "can't be blank"}
        end

        has_many :blogs

end

app/controllers/agents/confirmations_controller.rb
# frozen_string_literal: true

class Agents::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/agents/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Agents::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/agents/passwords_controller.rb
# frozen_string_literal: true

class Agents::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/agents/registrations_controller.rb
# frozen_string_literal: true

class Agents::RegistrationsController < Devise::RegistrationsController
  before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  def new
    #@results = Agent.where('prefecture_id IN(?)', params[:prefecture_id])
    super
  end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  def configure_sign_up_params
    devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute, :agentname, :agentname_kana, :first_name, :last_name, :first_name_kana, :last_name_kana, :prefecture_id, :address, :harbor, :how_to_go1, :how_to_go2, :tel1, :tel2, :homepage, :regular_holiday, :ice, :target, :ship_type_id, :fishing_type_id, :profile, :sheet, :image])
  end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/agents/sessions_controller.rb
# frozen_string_literal: true

class Agents::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/agents/unlocks_controller.rb
# frozen_string_literal: true

class Agents::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/agents_controller.rb
class AgentsController < ApplicationController

  def index
    @agents = Agent.all.order(created_at: :desc)
  end
  
  def show
    @agent = Agent.find(params[:id])
    @blogs = @agent.blogs.page(params[:page]).per(4).order(created_at: :desc)
    respond_to do |format|
      format.html
      format.js if request.xhr?
    end
  end

  def edit
    @agent = Agent.find(params[:id])
  end

  def update
    agent = Agent.find(params[:id])
    agent.update(agent_params)
    if agent.save
      flash[:notice] ="編集に成功しました"
      redirect_to agent_path(agent.id)
    else
      render :edit
    end
  end

  def agent_pref_index
    @tokyo = Agent.where(prefecture_id: 13)
  end
    
    

  private

def agent_params
  params.require(:agent).permit(:agentname, :agentname_kana, :first_name, :last_name, :first_name_kana, :last_name_kana, :prefecture_id, :address, :harbor,:how_to_go1, :how_to_go2, :tel1, :tel2, :homepage, :regular_holiday, :ice, :target, :ship_type_id, :fishing_type_id, :profile, :sheet, :image)
end

end

app/helpers/agents_helper.rb
module AgentsHelper
end

app/views/agents/_blog.html.erb
<%= paginate @blogs, remote: true%>
                  <% @blogs.each do |blog| %>
                      <li class='blog-list'>
                      <%= link_to blog_path(blog) do %>
                        <div class ='blog-content'>
                          <%= image_tag blog.image , class: "blog-img-thumb" %>
                          <p class ='blog-title-thumb'><%= blog.blog_title %></p>
                        </div>
                      <% end %>
                      </li>
                  <% end %>

app/views/agents/agent_pref_index.html.erb
<h1 class ='agent-index-tokyo'>東京都の船宿一覧</h1>

<div class="agent-index">
  <% @tokyo.each do |a| %>
  <%= link_to agent_path(a) do %>
    <div class='agent-index-content'>
    <% if a.image? %>
      <%= image_tag a.image.url, class: "icon_image" %>
    <% else %>
      <%= image_tag 'no_image.png', class: "icon_image" %>
    <% end %>
      <div class ='agent-index-name'>
        <%= a.agentname %>
      </div>
      <div class = 'agent-index-prefecture'>
        <%= Agent.prefectures.key(a.prefecture_id) %>
      </div>
    </div>
    <% end %>
  <% end %>
</div>

app/views/agents/edit.html.erb
<div class="agent-form-wrapper">
    <%= form_with model: @agent, url: agent_path(@agent.id), local: true do |f| %>
    <div class='form-wrap'>
      <div class='form-header'>
        <h1 class='form-header-text'>
          船宿情報編集
        </h1>
      </div>
      <div class="form-group">
        <div class='form-text-wrap'>
          <label class="form-text">プロフィール画像</label>
          <span class="indispensable">必須</span>
        </div>
          <%= f.file_field :image, class:"input-default",id:"agent_image" %>
      </div>
      <div class="form-group">
        <div class='form-text-wrap'>
          <label class="form-text">船名</label>
          <span class="indispensable">必須</span>
        </div>
          <%= f.text_area :agentname, class:"input-default", id:"agentname", placeholder:"釣り丸", maxlength:"40" %>
        </div>
      <div class="form-group">
        <div class='form-text-wrap'>
          <label class="form-text">船名カナ(全角)</label>
          <span class="indispensable">必須</span>
        </div>
          <%= f.text_area :agentname_kana, class:"input-default", id:"agentname_kana", placeholder:"ツリマル", maxlength:"40" %>
        </div>
      <div class="form-group">
        <p class='form-info-header'>
          船宿情報入力
        </p>
        <p class='form-info-text'>
          掲載に必要な情報となりますので必須欄の入力をお願いします。
        </p>
      </div>
      <div class="form-group">
        <div class='form-text-wrap'>
          <label class="form-text">お名前(全角)</label>
          <span class="indispensable">必須</span>
        </div>
        <div class='input-name-wrap'>
          <%= f.text_area :last_name, class:"input-name", id:"last-name", placeholder:"例) 山田" %>
          <%= f.text_area :first_name, class:"input-name", id:"first-name", placeholder:"例) 陸太郎" %>
        </div>
      </div>
      <div class="form-group">
        <div class='form-text-wrap'>
          <label class="form-text">お名前カナ(全角)</label>
          <span class="indispensable">必須</span>
        </div>
        <div class='input-name-wrap'>
          <%= f.text_area :last_name_kana, class:"input-name", id:"last-name-kana", placeholder:"例) ヤマダ" %>
          <%= f.text_area :first_name_kana, class:"input-name", id:"first-name-kana", placeholder:"例) リクタロウ" %>
        </div>
      </div>
      <div class="form-group">
        <div class='form-text-wrap'>
          <label class="form-text">都道府県</label>
          <span class="indispensable">必須</span>
        </div>
          <%= f.select(:prefecture_id, Agent.prefectures,{}, {class: 'hoge'}) %>
      </div>
      <div class="form-group">
        <div class='form-text-wrap'>
          <label class="form-text">住所</label>
          <span class="indispensable">必須</span>
        </div>
          <%= f.text_area :address, class:"input-default", id:"address", placeholder:"渋谷区渋谷○ー○ー○", maxlength:"40" %>
      </div>
      <div class="form-group">
        <div class='form-text-wrap'>
          <label class="form-text">港</label>
          <span class="indispensable">必須</span>
        </div>
          <%= f.text_area :harbor, class:"input-default", id:"harbor", placeholder:"渋谷港", maxlength:"40" %>
      </div>
      <div class="form-group">
        <div class='form-text-wrap'>
          <label class="form-text">車での行き方</label>
          <span class="indispensable">必須</span>
        </div>
          <%= f.text_area :how_to_go1, class:"input-default", id:"how_to_go1", placeholder:"〇〇インター出口を右折３個目の信号を左折で漁港です" %>
      </div>
      <div class="form-group">
        <div class='form-text-wrap'>
          <label class="form-text">公共機関での行き方</label>
          <span class="indispensable">必須</span>
        </div>
          <%= f.text_area :how_to_go2, class:"input-default", id:"how_to_go2", placeholder:"〇〇下車して２番線××経由▲▲行き□□下車" %>
      </div>
      <div class="form-group">
        <div class='form-text-wrap'>
          <label class="form-text">連絡先1</label>
          <span class="indispensable">必須</span>
        </div>
          <%= f.text_area :tel1, class:"input-default", id:"tel1", placeholder:"携帯・固定電話どちらでも可" %>
      </div>
      <div class="form-group">
        <div class='form-text-wrap'>
          <label class="form-text">連絡先2</label>
        </div>
          <%= f.text_area :tel2, class:"input-default", id:"tel2", placeholder:"携帯・固定電話どちらでも可" %>
      </div>
      <div class="form-group">
        <div class='form-text-wrap'>
          <label class="form-text">ホームページ</label>
        </div>
          <%= f.text_area :homepage, class:"input-default", id:"homepage", placeholder:"http://" %>
      </div>
      <div class="form-group">
        <div class='form-text-wrap'>
          <label class="form-text">定休日</label>
          <span class="indispensable">必須</span>
        </div>
          <%= f.text_area :regular_holiday, class:"input-default", id:"regular_holiday", placeholder:"火曜定休日" %>
      </div>
      <div class="form-group">
        <div class='form-text-wrap'>
          <label class="form-text">氷</label>
          <span class="indispensable">必須</span>
        </div>
          <%= f.text_area :ice, class:"input-default", id:"ice", placeholder:"サービス" %>
      </div>
      <div class="form-group">
        <div class='form-text-wrap'>
          <label class="form-text">席順</label>
          <span class="indispensable">必須</span>
        </div>
          <%= f.text_area :sheet, class:"input-default", id:"sheet", placeholder:"抽選" %>
      </div>
      <div class="form-group">
        <div class='form-text-wrap'>
          <label class="form-text">主なターゲット</label>
          <span class="indispensable">必須</span>
        </div>
          <%= f.text_area :target, class:"target", id:"target", placeholder:"マダイ・タチウオ" %>
      </div>
      <div class="form-group">
        <div class='form-text-wrap'>
          <label class="form-text">主な業種</label>
          <span class="indispensable">必須</span>
        </div>
          <%= f.select(:ship_type_id, Agent.ship_types,{}, {class: 'hoge'}) %>
      </div>
      <div class="form-group">
        <div class='form-text-wrap'>
          <label class="form-text">主な釣り方</label>
          <span class="indispensable">必須</span>
        </div>
          <%= f.select(:fishing_type_id, Agent.fishing_types,{}, {class: 'hoge'}) %>
      </div>
      <div class="form-group">
        <div class='form-text-wrap'>
          <label class="form-text">プロフィール</label>
          <span class='profile-input'>後ほど追加出来ます</span>
        </div>
          <%= f.text_area :profile, class:"input-default", id:"profile", placeholder:"自己紹介" %>
      </div>
      <div class="form-group">
        <h2 class='form-bottom-text'>
          「会員登録」のボタンを押すことにより、
          <span>利用規約</span>
          <br>に同意したものとみなします
        </h2>
      </div>
      <div class='register-btn'>
        <%= f.submit "会員登録" ,class:"register-red-btn" %>
      </div>
    </div>
    <div>
      <p class='register-info'>本人情報の登録について</p>
    </div>
  </div>
  <% end %>
  <div class ='angular-footer'>
    <div>
      <%= link_to '会員登録済みのかたはこちら', new_angler_session_path, class: 'register-info-2' %>
    </div>
    <div>
      <%= link_to 'パスワードをお忘れですか？', edit_angler_password_path, class: "register-info-2" %>
    </div>
  </div>
</div>

app/views/agents/index.html.erb
<div class="agent-index">
  <% @agents.each do |a| %>
  <%= link_to agent_path(a) do %>
    <div class='agent-index-content'>
    <% if @agent.image? %>
      <%= image_tag a.image.url, class: "icon_image" %>
      <% else %>
    <%= image_tag 'no_image.png', class: "icon_image" %>
    <% end %>
      <div class ='agent-index-name'>
        <%= a.agentname %>
      </div>
      <div class = 'agent-index-prefecture'>
        <%= Agent.prefectures.key(a.prefecture_id) %>
      </div>
    </div>
    <% end %>
  <% end %>
</div>

app/views/agents/show.html.erb
<div class = 'agent-show-main-container'>
    <div>
      <p class ='agent-profile-name-a'><%= @agent.agentname %> </p>
    </div>
    <div class ='icon_image_content'>
    <!--アイコンを設定していない場合の条件分岐-->
    <% if @agent.image? %>
    <%= image_tag @agent.image.url , class: "icon_image" %> 
    <% else %>
    <%= image_tag 'no_image.png', class: "icon_image" %>
    <% end %>
    </div>
      <div class="agent-show-container">
          <div class="container-fluid">
            <div class="row">
              <div class="tab-panels col-xs-12">
<!-- タブ -->
              <ul class="tabs">
                <li rel="panel-1" class="active"> 基本情報</li>
                <li rel="panel-2"> ブログ</li>
                <li rel="panel-3"> 投稿された釣果</li>
                <li rel="panel-4"> 予約情報</li>
              </ul>
  <!--基本情報の表示-->
              <div id="panel-1" class="panel active">
                <div class ='main-agent-profile-tab'>
                  <table>
                    <tr>
                      <th>ターゲット</th>
                      <td><%= @agent.target %></td>
                    </tr>
                    <tr>
                      <th>業種</th>
                      <td><%= Agent.ship_types.key(@agent.ship_type_id)%></td>
                    </tr>
                    <tr>
                      <th>釣り方</th>
                      <td><%= Agent.fishing_types.key(@agent.fishing_type_id)%></td>
                    </tr>
                    <tr>
                      <th>所在地</th>
                      <td><%= Agent.prefectures.key(@agent.prefecture_id) %><%= @agent.address%></td>
                    </tr>
                    <tr>
                      <th>港</th>
                      <td><%= @agent.harbor%></td>
                    </tr>
                    <tr>
                      <th>車での行き方</th>
                      <td><%= @agent.how_to_go1 %></td>
                    </tr>
                    <th>公共機関での行き方</th>
                      <td><%= @agent.how_to_go2 %></td>
                    </tr>
                    <tr>
                      <th>定休日</th>
                      <td><%= @agent.regular_holiday %></td>
                    </tr>
                    <tr>
                      <th>氷</th>
                      <td><%= @agent.ice %></td>
                    </tr>
                    <tr>
                      <th>席順</th>
                      <td><%=  @agent.sheet %></td>
                    </tr>
                    <tr>
                      <th>ホームページ</th>
                      <td><%= @agent.homepage %></td>
                    </tr>
                    <tr>
                      <th>連絡先1</th>
                      <td><%= @agent.tel1 %></td>
                    </tr>
                    <tr>
                      <th>連絡先2</th>
                      <td><%= @agent.tel2 %></td>
                    </tr>
                    <tr>
                      <th>船宿よりご案内</th>
                      <td><%= @agent.profile %></td>
                    </tr>
                  </table>
                </div>
                <br>
                <% if agent_signed_in? && current_agent.id == @agent.id %>
                  <div class='profile-edit-button'>
                    <%= link_to "プロフィールの編集", edit_agent_path, method: :get, class: 'profile-edit' %>
                  </div>
                <% end %>
              </div>
  <!--ブログ投稿一覧-->
              <div id="panel-2" class="panel">
                <p class ='blog-list-tab'><%= @agent.agentname %>さんのブログ</p>
                <div class= 'panel2-blog-tab'>
                  <div id="items">
                    <%= render :partial => 'shared/blog' %>
                  </div>
                </div>
              </div>
  <!--釣果投稿一覧-->
              <div id="panel-3" class="panel">
                <p> ここは釣果投稿ユーザーが投稿した船宿をタグ付けした釣果が載ります</p>
              </div>
              <div id="panel-4" class="panel">
                <p> ここは予約機能が表示されます。船宿側は予約枠の設定と予約の管理ができて釣果投稿側は予約枠の確認と予約ができます。</p>
              </div>
            </div>
          </div> 
      </div> 
</div>

app/views/agents/show.js.erb
$("#items").html("<%= escape_javascript(render :partial => 'shared/blog', object: @blogs) %>");