config/routes.rb
Rails.application.routes.draw do
  
  devise_for :anglers, controllers: {
    sessions:      'anglers/sessions',
    passwords:     'anglers/passwords',
    registrations: 'anglers/registrations'
    }

    devise_for :agents, controllers: {
      sessions:      'agents/sessions',
      passwords:     'agents/passwords',
      registrations: 'agents/registrations'
    }
    root  'top#index'
    resources :agents, only: [:show,:edit,:update,:index]
    resources :blogs
    resources :posts, only: [:new, :create, :index, :show, :edit, :update, :destroy]

    get  'agents/prefecture_id/tokyo',  to: 'agents#agent_pref_index'

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AnyFishApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link rel="stylesheet" type="text/css" href="http://yui.yahooapis.com/3.18.1/build/cssreset/cssreset-min.css">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/bxslider/4.2.12/jquery.bxslider.css">
    <link rel="stylesheet" type="text/css" href="//cdn.jsdelivr.net/npm/slick-carousel@1.8.1/slick/slick.css"/>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script type="text/javascript" src="//cdn.jsdelivr.net/npm/slick-carousel@1.8.1/slick/slick.min.js"></script>
    <script src="js/agent_tabmenu.js"></script>

  </head>

  <body>
  <header>
      <div class = 'header-base'>
        <!-- ロゴとタイトル -->
        <div class = 'header-logo'>
        <%= link_to image_tag('header-logo.png' , class: 'logo-image'), "/" %>
          <%= image_tag 'header-title.png', class: 'title-image'%>
        </div>
        <!-- //ロゴとタイトル -->
        <!-- メニューボタン -->
        <div class = 'header-button'>
          <div class = 'guide-button'>
            <a href="#">初心者ガイド</a>
          </div>
          <div class = 'result-button'>
            <a href="/posts">釣果一覧</a>
          </div>
          <div class = 'result-button'>
            <%= link_to '船宿一覧', agents_path(@agents) %>
          </div>
          <div class = 'ranking-button'>
            <a href="#">ランキング</a>
          </div>
        </div>
        <!-- //メニューボタン -->
        <!-- 検索窓 -->
        <div class = 'header-search'>
          <%= form_with(url:'#', local: true, method: :get, class: "header-search") do |form| %>
            <%= form.text_field :keyword, placeholder: "検索する", class: "search-input" %>
            <button type = 'submit', class='search-button'><%= image_tag 'search-image.png', class: 'search-logo'%></button>
          <% end %>
          
        </div>
        <!-- //検索窓 -->
        <!-- ユーザー管理 -->
        <!-- ログインで表示を変える -->
        <div class = 'header-user'>
          <% if angler_signed_in? %>
          <div class = 'username'>
            <p>こんにちは<%= link_to current_angler.nickname, "#", class: "username" %>さん</p>
          </div>
          <div class = 'tweet-button'>
            <%= link_to 'Sign out', destroy_angler_session_path, method: :delete, class: "logout" %>
          </div>
          <% elsif agent_signed_in? %>
          <div class = 'username'>
            <p>こんにちは<%= link_to current_agent.agentname, agent_path(current_agent.id), class: "username" %>さん</p>
          </div>
          <% else %>
          <div class = 'login'>
            <%= link_to 'Sign in', new_angler_session_path, class: "login" %>
          </div>
          <div class = 'sign-up'>
            <%= link_to 'Sign up', new_angler_registration_path, class: "sign-up" %>
          </div>
          <% end %>
        </div>
        <!-- //ログインで表示を変える// -->
      </div>
    </header>

    <%= yield %>

    <footer>
    <svg viewBox="0 0 120 28">
  <defs> 
    <mask id="xxx">
      <circle cx="7" cy="12" r="40" fill="#fff" />
    </mask>
    
    <filter id="goo">
      <feGaussianBlur in="SourceGraphic" stdDeviation="2" result="blur" />
      <feColorMatrix in="blur" mode="matrix" values="
            1 0 0 0 0  
            0 1 0 0 0  
            0 0 1 0 0  
            0 0 0 13 -9" result="goo" />
      <feBlend in="SourceGraphic" in2="goo" />
    </filter>
      <path id="wave" d="M 0,10 C 30,10 30,15 60,15 90,15 90,10 120,10 150,10 150,15 180,15 210,15 210,10 240,10 v 28 h -240 z" />
  </defs> 

    <use id="wave3" class="wave" xlink:href="#wave" x="0" y="-2" ></use> 
    <use id="wave2" class="wave" xlink:href="#wave" x="0" y="0" ></use>

  <g class="topball">
  <circle class="ball" cx="110" cy="8" r="4" stroke="none" stroke-width="0" fill="red" />

    <g class="arrow">
    <polyline class="" points="108,8 110,6 112,8" fill="none"  />
    <polyline class="" points="110,6 110,10.5" fill="none"  />
    </g>
    
  </g>
  <g class="gooeff">
  <circle class="drop drop1" cx="20" cy="2" r="1.8"  />
  <circle class="drop drop2" cx="25" cy="2.5" r="1.5"  />
  <circle class="drop drop3" cx="16" cy="2.8" r="1.2"  />
    <use id="wave1" class="wave" xlink:href="#wave" x="0" y="1" />
  
    <!-- g mask="url(#xxx)">
    <path   id="wave1"  class="wave" d="M 0,10 C 30,10 30,15 60,15 90,15 90,10 120,10 150,10 150,15 180,15 210,15 210,10 240,10 v 28 h -240 z" />
    </g-->
  </g >

</svg>

  <div class = 'footer-top'>Any fish © 2021 RISA IWATA</div>
      <div class = 'footer-content'>
        <div class = 'footer-left'>
          <h2 class = 'site-nemu'> サイト概要</h2>
            <div class = 'site-menu-left-content'>
              <p>ホーム</p>
              <p>釣果投稿</p>
              <p>釣果一覧</p>
              <p>船宿一覧</p>
              <p>船宿ブログ</p>
            </div>

            <div class = 'site-menu-right-content'>
              <p>タイドグラフ</p>
              <p>Any fish通信</p>
              <p>魚図鑑</p>
              <p>初心者ガイド</p>
              <p>タックル検索</p>
            </div>
          </div>

        <div class ='footer-center'>
        <p>運営情報</p>
        <p>ごあいさつ</p>
        <p>お問い合わせ</p>
        </div>
        <div class ='footer-right'>
        <%= image_tag 'logo_transparent_正規.png', class: 'footer-logo-image'%>
        <%= image_tag 'footer-logo.png', class: 'footer-str-image'%>
        </div>
    </footer>
  </body>
</html>